#pragma once

#include <errno.h>

#define CUSTOM_ERROR_CODE(x) (2000 + x)

// TODO: Make more aliases for common errors

#define ERROR_UNDEFINED CUSTOM_ERROR_CODE(1)
#define ERROR_INVALID_STATE CUSTOM_ERROR_CODE(2)
#define ERROR_INVALID_ARGUMENT EINVAL
#define ERROR_MISSING_PARAMETER CUSTOM_ERROR_CODE(3)
#define ERROR_NOT_FOUND CUSTOM_ERROR_CODE(4)

