#pragma once

#include <sys/errno.h>

#define CUSTOM_ERROR_CODE(x) (-__ELASTERROR - x)

#define ERROR_UNDEFINED CUSTOM_ERROR_CODE(1)
#define ERROR_INVALID_STATE CUSTOM_ERROR_CODE(2)
#define ERROR_INVALID_PARAMETER CUSTOM_ERROR_CODE(3)
#define ERROR_MISSING_PARAMETER CUSTOM_ERROR_CODE(4)
