general.vendor=CL-32
general.name=CL-32 v0.2 v0.3

hardware.target=ESP32S3
hardware.flashSize=16MB
hardware.spiRam=true
hardware.spiRamMode=QUAD
hardware.spiRamSpeed=80M
hardware.spiRamXipDisabled=true
hardware.esptoolFlashFreq=80M
hardware.bluetooth=true

storage.userDataLocation=SD

display.size=2.9"
display.dpi=139

lvgl.colorDepth=8
lvgl.theme=Mono
lvgl.uiDensity=compact

cdn.infoMessage=This variant supports hardware revision v0.2 and v0.3.
