general.vendor=Seeed Studio
general.name=Wio Tracker L2 Pro

hardware.target=ESP32S3
hardware.flashSize=16MB
hardware.spiRam=true
hardware.spiRamMode=OCT
hardware.spiRamSpeed=80M
hardware.esptoolFlashFreq=80M
hardware.tinyUsbMsc=true
hardware.bluetooth=true

storage.userDataLocation=SD

display.size=3.2"
display.shape=rectangle
display.dpi=125

lvgl.colorDepth=16
