#!/usr/bin/env python3
"""
Generates the font resources:
- Data/system/fonts/AdwaitaSans.ttf: text font TTF subset with the supported characters
- Data/system/fonts/AdwaitaMono.ttf: monospace font TTF subset for the terminal (ASCII)
- Tactility/Private/Tactility/lvgl/FontVersions.h: versions of the subsets, for font cache invalidation

The fonts are rasterized from the TTF subsets on device. The text fonts include every character of
their subset, so TEXT_CODEPOINT_RANGES determines the supported characters.

Requires the fonttools package: pip install fonttools
"""
import os
import zlib

from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

# Variable font weight of the text font: 100 (Thin) to 900 (Black), 400 is Regular
TEXT_WEIGHT = 550

# Inclusive ranges
TEXT_CODEPOINT_RANGES = [
    (0x0020, 0x007E), # ASCII
    (0x00A0, 0x00FF), # Latin-1 Supplement
    (0x2010, 0x2027), # Dashes, quotes, bullet, ellipsis
    (0x2030, 0x203A), # Per mille, primes, angle quotes
    (0x20AC, 0x20AC), # Euro sign
]

MONO_CODEPOINT_RANGES = [
    (0x0020, 0x007E), # ASCII
]

base_dir = os.path.dirname(os.path.abspath(__file__))
output_dir = os.path.join(base_dir, "..", "..", "Data", "system", "fonts")
version_header_path = os.path.join(base_dir, "..", "Private", "Tactility", "lvgl", "FontVersions.h")

def generate_subset(source_file: str, output_file: str, codepoint_ranges: list, weight=None) -> int:
    """Writes a TTF subset and returns its version (crc32)"""
    output_path = os.path.join(output_dir, output_file)
    print(f"Generating {output_path}")
    font = TTFont(os.path.join(base_dir, source_file), recalcTimestamp=False)
    if "fvar" in font:
        # Pin the weight axis and all other axes to their defaults
        axis_values = {axis.axisTag: None for axis in font["fvar"].axes}
        if weight is not None:
            axis_values["wght"] = weight
        font = instancer.instantiateVariableFont(font, axis_values)
    options = subset.Options()
    options.layout_features = []
    options.drop_tables += ["GSUB", "GPOS", "GDEF"]
    options.hinting = False
    options.notdef_outline = True
    subsetter = subset.Subsetter(options)
    subsetter.populate(unicodes=[cp for first, last in codepoint_ranges for cp in range(first, last + 1)])
    subsetter.subset(font)
    os.makedirs(output_dir, exist_ok=True)
    font.save(output_path)
    with open(output_path, "rb") as f:
        return zlib.crc32(f.read()) & 0xFFFFFFFF

text_version = generate_subset("AdwaitaSans-Regular.ttf", "AdwaitaSans.ttf", TEXT_CODEPOINT_RANGES, TEXT_WEIGHT)
mono_version = generate_subset("AdwaitaMono-Regular.ttf", "AdwaitaMono.ttf", MONO_CODEPOINT_RANGES)

print(f"Generating {version_header_path}")
with open(version_header_path, "w") as f:
    f.write("#pragma once\n\n")
    f.write("// Generated by Tactility/Fonts/generate.py\n")
    f.write("// The versions change whenever the TTF subsets change\n")
    f.write(f"#define TT_TEXT_FONT_VERSION 0x{text_version:08X}u\n")
    f.write(f"#define TT_MONO_FONT_VERSION 0x{mono_version:08X}u\n")
