/* Generated by LSS. Do not edit. */

#ifndef LV_THEME_MATERIAL_MONO_H
#define LV_THEME_MATERIAL_MONO_H

#include <lvgl.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    bool is_dark;
    bool is_compact;
    bool animations_enabled;
    lv_color_t color_primary;
    lv_color_t color_secondary;
    const lv_font_t * font_small;
    const lv_font_t * font_normal;
    const lv_font_t * font_large;
} lv_theme_material_mono_config_t;

/**
 * Reset a config to its default values
 * @param config the config to initialize
 */
void lv_theme_material_mono_config_init(lv_theme_material_mono_config_t * config);

/**
 * Initialize the theme
 * @param disp pointer to display (NULL for the default display)
 * @param config the theme config, which is copied
 * @return a pointer to reference this theme later
 */
lv_theme_t * lv_theme_material_mono_init(lv_display_t * disp, const lv_theme_material_mono_config_t * config);

/**
 * Check if the theme is initialized
 * @return true if initialized, false otherwise
 */
bool lv_theme_material_mono_is_inited(void);

/**
 * Get the theme
 * @return a pointer to the theme, or NULL when not initialized
 */
lv_theme_t * lv_theme_material_mono_get(void);

/**
 * Deinitialize the theme
 */
void lv_theme_material_mono_deinit(void);

#ifdef __cplusplus
}
#endif

#endif /* LV_THEME_MATERIAL_MONO_H */
