general.vendor=WaveShare
general.name=S3 Touch LCD 1.47"
general.incubating=true

apps.launcherAppId=Launcher
apps.autoStartAppId=ApWebServer

hardware.target=ESP32S3
hardware.flashSize=16MB
hardware.spiRam=true
hardware.spiRamMode=OCT
hardware.spiRamSpeed=120M
hardware.tinyUsb=true
hardware.esptoolFlashFreq=120M
hardware.bluetooth=true

display.size=1.47"
display.shape=rectangle
display.dpi=247

cdn.warningMessage=Touch doesn't work yet

lvgl.colorDepth=16
lvgl.uiDensity=compact
