[device]
name=CYD 2432S022C
model=ESP32-2432S022C

[esp32]
chip=ESP32
variant=ESP32-WROOM-32
flashSize=4MB
flashFreq=40M
spiRam=false

[display]
size=2.2"
resolution=240x320
driver=ST7789
interface=I8080