[general]
vendor=Waveshare
name=S3 Touch AMOLED 1.8"
incubating=true

[apps]
launcherAppId=Launcher
autoStartAppId=

[hardware]
target=ESP32S3
flashSize=16MB
spiRam=true
spiRamMode=OCT
spiRamSpeed=80M
tinyUsb=true
esptoolFlashFreq=80M

[display]
shape=rectangle
dpi=310
width=368
height=448

[lvgl]
colorDepth=16
uiDensity=compact
fontSize=14
statusbarIconSize=16
launcherIconSize=36

[sdkconfig]
CONFIG_I2C_SKIP_LEGACY_CONFLICT_CHECK=y
CONFIG_SPIRAM_TRY_ALLOCATE_WIFI_LWIP=n