general.vendor=LilyGO
general.name=T-Embed CC1101 Plus

apps.launcherAppId=tactility.launcher

hardware.target=ESP32S3
hardware.flashSize=16MB
hardware.spiRam=true
hardware.spiRamMode=OCT
hardware.spiRamSpeed=80M
hardware.spiRamXipDisabled=true
hardware.tinyUsbMsc=true
hardware.esptoolFlashFreq=80M
hardware.bluetooth=true

storage.userDataLocation=SD

display.size=1.9"
display.shape=rectangle
display.dpi=191

lvgl.colorDepth=16
lvgl.fontSize=16
lvgl.uiDensity=compact

sdkconfig.CONFIG_CODEC_DUMMY_SUPPORT=y


