[general]
vendor=Waveshare
name=S3 Touch AMOLED 2.06"
incubating=true

[apps]
launcherAppId=Launcher

[hardware]
target=ESP32S3
flashSize=32MB
spiRam=true
spiRamMode=OCT
spiRamSpeed=120M
tinyUsb=true
esptoolFlashFreq=120M

[display]
shape=rectangle
dpi=326
width=410
height=502

[lvgl]
colorDepth=16
uiDensity=default
fontSize=22
statusbarIconSize=18
launcherIconSize=18

[sdkconfig]
CONFIG_I2C_SKIP_LEGACY_CONFLICT_CHECK=y
CONFIG_BSP_I2C_FAST_MODE=y
CONFIG_BSP_I2C_CLK_SPEED_HZ=400000
CONFIG_TASK_WDT_TIMEOUT_S=10
CONFIG_SPIRAM_MALLOC_RESERVE_INTERNAL=131072
CONFIG_ESP_PHY_ENABLE_USB=y
CONFIG_FREERTOS_GENERATE_RUN_TIME_STATS=y
CONFIG_SPI_FLASH_HPM_ENA=y
CONFIG_ESPTOOLPY_FLASH_MODE_AUTO_DETECT=n
CONFIG_BOOTLOADER_FLASH_DC_AWARE=y
CONFIG_LV_OS_FREERTOS=y
CONFIG_LV_DEF_REFR_PERIOD=15
CONFIG_LV_DRAW_SW_DRAW_UNIT_CNT=1
CONFIG_LV_ATTRIBUTE_FAST_MEM_USE_IRAM=y

