general.vendor=LilyGO
general.name=T-Deck Pro
# The display driver is not reliable yet
general.incubating=true

apps.launcherAppId=tactility.launcher

hardware.target=ESP32S3
hardware.flashSize=16MB
hardware.flashMode=DIO
hardware.spiRam=true
hardware.spiRamMode=AUTO
hardware.spiRamSpeed=80M
hardware.tinyUsbMsc=true
hardware.esptoolFlashFreq=80M
hardware.bluetooth=true

storage.userDataLocation=SD

display.size=3.1"
display.shape=rectangle
display.dpi=128

lvgl.colorDepth=8
lvgl.theme=Mono
lvgl.statusbarColorsInverted=true

cdn.warningMessage=Only for hardware revision 1.0! Display not reliably working. Use at your own risk.
