name: Build

inputs:
  board_id:
    description: The sdkconfig file to build
    required: true
  arch:
    description: The ESP32 SOC variant
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: 'Board select'
      shell: bash
      run: python device.py ${{ inputs.board_id }}
    - name: 'Build'
      uses: espressif/esp-idf-ci-action@v1
      with:
        # NOTE: Update with ESP-IDF!
        esp_idf_version: v5.5
        target: ${{ inputs.arch }}
        path: './'
    - name: 'Release'
      shell: bash
      env:
        # NOTE: Update with ESP-IDF!
        ESP_IDF_VERSION: '5.5'
      run: python Buildscripts/release-sdk.py release/TactilitySDK
    - name: 'Test Integration'
      shell: bash
      working-directory: Tests/HelloWorld
      env:
        # NOTE: Update with ESP-IDF!
        ESP_IDF_VERSION: '5.5'
        TACTILITY_SDK_PATH: '../../release/TactilitySDK'
      run: python.py tactility.py build ${{ inputs.arch }} --local-sdk
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: TactilitySDK-${{ inputs.arch }}
        path: release/TactilitySDK
        retention-days: 30
