// SPDX-License-Identifier: Apache-2.0
// Generated by generate-icons.py

#include <lvgl/icons/names.h>

const char* const lvgl_icon_shared_names[] = {
    "add",
    "apps",
    "area_chart",
    "app_registration",
    "calendar_month",
    "cable",
    "circle",
    "close",
    "cloud",
    "check",
    "delete",
    "devices",
    "display_settings",
    "edit_note",
    "electric_bolt",
    "folder",
    "deployed_code",
    "download",
    "forum",
    "gamepad",
    "help",
    "hub",
    "image",
    "keyboard_arrow_up",
    "lightbulb",
    "language",
    "lists",
    "mail",
    "menu",
    "mop",
    "more_vert",
    "music_note",
    "note_add",
    "palette",
    "power_settings_new",
    "refresh",
    "search",
    "settings",
    "toolbar",
    "navigation",
    "keyboard_alt",
    "usb",
    "wifi",
    "bluetooth",
    "terminal",
    "logo_dev",
    "camera",
    "lightstrip",
};

const size_t lvgl_icon_shared_name_count = sizeof(lvgl_icon_shared_names) / sizeof(lvgl_icon_shared_names[0]);

const char* const lvgl_icon_statusbar_names[] = {
    "location_on",
    "location_off",
    "cloud",
    "memory",
    "sd_card",
    "sd_card_alert",
    "signal_wifi_0_bar",
    "network_wifi_1_bar",
    "network_wifi_2_bar",
    "network_wifi_3_bar",
    "signal_wifi_4_bar",
    "signal_wifi_off",
    "signal_wifi_bad",
    "battery_android_frame_1",
    "battery_android_frame_2",
    "battery_android_frame_3",
    "battery_android_frame_4",
    "battery_android_frame_5",
    "battery_android_frame_6",
    "battery_android_frame_full",
    "battery_android_frame_bolt",
    "bluetooth",
    "bluetooth_searching",
    "bluetooth_connected",
    "bluetooth_disabled",
    "usb",
};

const size_t lvgl_icon_statusbar_name_count = sizeof(lvgl_icon_statusbar_names) / sizeof(lvgl_icon_statusbar_names[0]);

const char* const lvgl_icon_launcher_names[] = {
    "apps",
    "folder",
    "settings",
};

const size_t lvgl_icon_launcher_name_count = sizeof(lvgl_icon_launcher_names) / sizeof(lvgl_icon_launcher_names[0]);

